server:
    port: 8282
spring:
    application:
        name: ms-gateway
    cloud:
    # Manual
        gateway:
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: 
                            - http://localhost:4200
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
        routes:
            - id: ms-customer
              uri: lb://ms-customer
              predicates:
                - Path=/ms-customer/**
              filters:
                - RewritePath=/ms-customer/(?<path>.*), /$\{path}
            - id: ms-account
              uri: lb://ms-account
              predicates:
                - Path=/account/**
              filters:
                - RewritePath=/account/(?<path>.*), /$\{path}  
        # Automatico 
        # gateway:
        #     discovery:
        #         locator:
        #             enabled: true
        #             lower-case-service-id: true


# Establecemos que endpoints del actuator queremos habilitar
management:
    endpoints:
        web:
            exposure:
                include: gateway
eureka:
    client:
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
